version: '3'

services:
  airco_db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - 5678:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - airco_db_volume

  airco_data_puller:
    build:
      context: ./DataPuller
      dockerfile: Dockerfile
    ports:
      - 5555:5000
    depends_on:
      - airco_db

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - TZ=Europe/Brussels
    volumes:
    - grafana_volume

volumes:
  airco_db_volume:
    driver: local
  grafana_volume:
    driver: local


